---
# tasks/configure.yml (redis)
# Prefix : (redis)

- name: Create redis.conf
  include_tasks: "deploy_redis_conf.yml"
  loop: "{{ __redis_instances }}"
  loop_control:
    loop_var: instance
  vars:
    __redis_instances: |
      {% if redis_enable_multi_instance %}
      {%   set __tmp_list = [] %}
      {%   for _instance, _conf in __redis_combined_conf.items() %}
      {%     set _ = __tmp_list.append(_instance) %}
      {%   endfor %}
      {{   __tmp_list }}
      {% else %}
      {{ ['default'] }}
      {% endif %}
