---
# tasks/main.yml (redis)
# Prefix : (redis)

- name: Install tasks
  import_tasks: install.yml
  when:
    - redis_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
